### PR TITLE
Show progress on preview & improve execution end detection

### LINKED ISSUE #14: Show progress in VSCode
I came across the [Progress API](https://code.visualstudio.com/api/extension-capabilities/common-capabilities#progress-api) to show progress like in [this sample extension](https://github.com/microsoft/vscode-extension-samples/tree/main/progress-sample):

preview

Then I had the following idea:
- When sending the command to Manim, get back the terminal stdout stream where Manim outputs its progress
- Process that string a bit to make it nicely readable inside a popup
- Show the continuous progress as running notification

In the long-term: why do users even have to interact with the Terminal to see Manim output? The only contact point is if you want to run your own quick commands in the interactive shell. But honestly, I'd rather just create a new Manim Cell and preview that one as it's more comfortable to program in the editor instead of a terminal. I'm not demanding to take away the possibility to have the terminal opened. But this could be opt-in for "advanced" users while keeping others in VSCode itself. They could click on "Preview Manim Cell" and see the progress directly as discussed here.

The tricky part is getting the stream of a terminal. I've experimented a bit with the new Terminal API and didn't get it to work (but I didn't also try for too long). If you want to try it, [this is a good StackOverflow answer](https://stackoverflow.com/a/77456264/9655481).

### PR DESCRIPTION
**Pull request by Splines**
Closes #14.

This is a further step towards a terminal-free workflow. Here we add add **notifications that show the current progress of the executed Manim command**, e.g. which part of the scene is executing and with which percentage. Furthermore, we show an infinite progress when a new Manim session is started.

### Feature preview
https://github.com/user-attachments/assets/31a7df17-75cb-43a9-b674-31eca9956880

In the preview, note how the shell is automatically opened if any command has to send a keyboard interrupt. This is because VSCode itself opens the terminal in this case. This is a known limitation and won't be fixed in this PR.

### Further off-topic changes

- When the user opens a new terminal and executes `manimgl` manually in there, we close a Manim session that is open in another terminal. This is to avoid multiple open Manim sessions at the same time.
- ⚠ The detection of the end of a command execution (like code preview) was made more robust **by also taking the IPython cell count into consideration** to avoid false positives. See for example [this comment](https://github.com/bhoov/manim-notebook/pull/33#issuecomment-2440150900).
- On Linux, it is currently possible to interrupt a running command. When doing so, a `Ctrl+C` is sent. Starting with this PR, we manually send the `Ctrl+C` instead to know exactly when this happens and to therefore render our control flow more easy. This also has the advantage that we could add other commands to send there, e.g. when we find an alternative on MacOS since `Ctrl+C` in Interactive Manim is apparently not working there, see #16.

### CODE REVIEW

**Comment by bhoov** [comment]
Feature is really nice, but I'm getting a bug on my MacOS system where the changes in this PR break my ability to run a cell. Somehow, the extension always thinks that an existing command is already running. See video below.

https://github.com/user-attachments/assets/93863196-6646-48ab-bac2-4ad868ee9ffc

**Comment by Splines** [comment]
@bhoov Could you test it again now? If the error persists, could you replace [these lines](https://github.com/bhoov/manim-notebook/blob/db998a54ec7823c82070d3bc1159be29b9fe6e2f/src/manimShell.ts#L409-L414) by the following and see if it work?

```js
this.eventEmitter.once(ManimShellEvent.IPYTHON_CELL_FINISHED, resolve);
```

**Comment by bhoov** [comment]
If I replace the specified lines with your suggestion, it works as normal. Is this the recommended fix?

**Comment by Splines** [comment]
> If I replace the specified lines with your suggestion, it works as normal. Is this the recommended fix?

No, it just tells me that we experience different behaviors. For me, when issuing the command, I receive the command just sent in the data stream. Therefore, I have to skip on `In [42]:` before matching the actual end. Otherwise, I issue the command, get back the command itself as string and will think that the command is not executing anymore.

In the terminal, do you notice that sometimes empty `In [...]:` blocks are executed? E.g. two `In [8]` in a row? (where the `8` is not incremented

**Comment by bhoov** [comment]
No, i have not noticed this at all, though I have only just now run a few tests.

**Comment by Splines** [comment]
Could you add the following before [this line](https://github.com/bhoov/manim-notebook/blob/db998a54ec7823c82070d3bc1159be29b9fe6e2f/src/manimShell.ts#L442):

```js
console.log(`🎯: ${data}`);
```

Then do some experiments and send me the log?

**Comment by bhoov** [comment]
Not sure what you are looking for. Here is what is shown in the `debug console` on my machine for a few random cells in the example_scenes.py

[debug-macos.log](https://github.com/user-attachments/files/17535221/debug-macos.log)

**Comment by Splines** [comment]
As an example: when I manually type `ls` in the terminal, then press enter, I see this output:

image

Here you see why I skip the first `In [12]`. Maybe to make this more robust I could store the number of the cell where we execute the command in, and then wait for the `counter + 1` cell to arrive.

**Comment by bhoov** [comment]
I will revisit this bug when I get back home. Thx @splines!

**Comment by Splines** [comment]
Ok, could you also add the following before [this line](https://github.com/bhoov/manim-notebook/blob/db998a54ec7823c82070d3bc1159be29b9fe6e2f/src/manimShell.ts#L379):

```js
console.log(`🌟: ${command}`);
```

and then send me the log again? Since your previous log seems pretty normal. I have to find out when the command is issued and when you get this info in the datastream. If this is similar for us both, there's another reason why this is not working for you.

[wsl-preview.log](https://github.com/user-attachments/files/17535270/wsl-preview.log)

**Comment by Splines** [comment]
In the last commits, I've made the detection of the end of a cell execution more robust. Please try it out again on MacOS. I've also added missing docstrings and explained off-topic changes in the PR comment.

I've left some console log statements to ease debugging (sending logfiles) in case if it still does not work on MacOS. In contrary, if it works and you approve, please remove all five `console.log` statements.

Upon merging please remove all commits prior to 6cad6ec (`Prevent multiple commands from running on MacOS`) from the squash-commit message. After that, some commits are still from other branches, but it's probably useless and too much effort to filter them out.

**Review by bhoov — APPROVED** [review]
Yer a wizard @Splines

**Comment by bhoov** [comment]
Omg, everything works as expected and the whole extension is starting to feel very polished on my end <3

**Pull request merged**
