### PR TITLE
fix #18

### LINKED ISSUE #18: executeCommand() doesn't execute the checkpoint_paste() command
Terminals: GitBash and Conda through Powershell and GitBash
Issue replicated on 2 different PCs both Windows 11 one Enterprise and one Education (Version 23H2)
IPython version: 8.21.0

I've downloaded the repository, npm installed, npm compiled everything and attached the debugger.

Simple Manim Scene:

```py
from manimlib import *

class SubTensors(InteractiveScene):
    def construct(self):
        ## Interactions
        circle = Circle(radius = 2)
        self.play(DrawBorderThenFill(circle))
```

Detects the preview cell.
Run the command:

```sh
manimgl sub_tensor.py SubTensors -se 5
```

And when I click on the Preview Manim Cell, it clears the console, writes checkpoint_paste() but doesn't run it at all.

With the debugger, I can see that with both the `executeCommand` and `terminal.sendText`, the command is not executed.
If then I manually click ENTER in terminal, the command is executed, however it's now too late, the clipboard is already reset to the previous state and throws an error because it tries to run something that is not python code.

Since this happens with different terminals, I believe it's something due to the IPython console. Because if we just click `Preview Manim Cell`, without running the `manimgl` command, the command `checkpoint_paste()` is executed properly (even though, in this case, it's an error, since it's not recognized as a Powershell/Bash/Conda command).

What I have already tried:
 - Adding `\r\n` or `\n` at the end of the `PREVIEW_COMMAND` string
 - Adding spaces or other chars at the end of the `PREVIEW_COMMAND` string
 - `terminal.sendText` actually has a second parameter that is used to execute the command, setting that to `true`
 - Executing always `sendText` regardless if the terminal supports `shellIntegration`

Nothing worked. Any ideas as to why would this happen? I'm not familiar with the IPython console; it may have some weird interaction behaviour.

### PR DESCRIPTION
**Pull request by VladimirFokow**
integrates the @mitkonikov's solution, in issue #18

### CODE REVIEW

**Comment by Splines** [comment]
So we don't want to do PR reviews anymore?

**Comment by VladimirFokow** [comment]
my bad, sorry

What should we do before merging each PR?

**Comment by Splines** [comment]
> Is it possible to make it a hard requirement in GitHub? Should we?

Yes, it's possible to define branch protection rules in GitHub and I think we definitely should, @bhoov. Even for small changes, it's worth to have another pair of eyes look over code.

Maybe something like at least one review required? Or if you want to look over every PR then you can also define that at least one review is required from the author.

**Comment by bhoov** [comment]
Last night i made you both "collaborators" on this repo when I realized I could not request either of you to be "reviewers" on my own PR. Also, between my job, school, and an 18 month old I'm barely keeping up with both of your paces of development 🙈. 

I am happy with a rule that says we need at least 1 other reviewer for each PR. I do not need to be that reviewer, but I will try to monitor all PRs in these early stages of development.

Additionally, what do you think of the following plan:
1. Protecting the `main` branch. This will be our primary branch for development
2. Making a new `deploy` branch that will contain the state of the code that is currently deployed to the marketplace

**Comment by Splines** [comment]
> Also, between my job, school, and an 18 month old I'm barely keeping up with both of your paces of development 🙈.

Yeah, totally understandable. In the long-term I will also not be able to keep up this pace, this is probably just in the beginning phase until we reach a point that is somewhat stable. And even for now, I'm in uni and each week might be different with regards to how much time I can spare for a bit of development on the side. I mean, no ones pays us to do this ;)

> Additionally, what do you think of the following plan:

I like the plan of having separate branches. Just out of convention in other projects, what do you think about using a `main` and a `dev` branch instead? Where the `main` branch is tagged and each tag corresponds to one release on the marketplace. It doesn't have any advantages (maybe just a tiny one that `main` is usually the default branch and therefore when viewing the repo, you see production-ready code and not dev code. But that's really not too important).

Then, from time to time we can do a `Continuous Release 0.x`, which is just a PR from `dev` to `main`. So
- *squash and merge* from `feature/my-branch` or `fix/my-branch` to `dev`
- *merge commit* from `dev` to `main` and after that deploy to marketplace. At [MaMpf](https://github.com/MaMpf-HD/mampf), we've even set it up such that each tag creation on `main` triggers a webhook to our server and there it automatically redeploys the website.

Note that at MaMpf, I've also aggregated some conventions that we use for Git in a [wiki entry](https://github.com/MaMpf-HD/mampf/wiki/GitHub%E2%80%90related). E.g. it also includes the convention for [commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) (which I use for PR titles as well, e.g. capitalize the start, not too long, in imperative form).

**Comment by Splines** [comment]
Also note that with us being collaborators now, @VladimirFokow, we can directly create branches on this repo (such that I don't have to add remote repos/forks to my `git remote -v` list to checkout the branch ;))

**Pull request merged**
